# Generated by Django 5.1.5 on 2025-04-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=None, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
